### ISSUE TITLE
truffle v5対応

### ISSUE THREAD

**Issue by kazuakiishiguro** [connectometo/marketplace-mvp#159]

**Comment by kazuakiishiguro** [comment]
https://ethereum.stackexchange.com/questions/65805/truffle-contract-error-number-can-only-safely-store-up-to-53-bits

maybe truffle v5 error?
so I leave this issue as 'wont fix '

```
Contract: Bonding Curve Contract
       curve calculations
         should calculate correctly:
     Error: Number can only safely store up to 53 bits
      at assert (node_modules/truffle/build/webpack:/~/number-to-bn/~/bn.js/lib/bn.js:6:1)
      at BN.toNumber (node_modules/truffle/build/webpack:/~/number-to-bn/~/bn.js/lib/bn.js:506:1)
      at Context.it (test/PriceCurve.js:38:64)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
